### ISSUE TITLE
Impossible to build with TS

### ISSUE THREAD

**Issue by MALVEBaptiste** [mondeja/svg-path-bbox#120]
Hello i can't build my project i have this error : 

error TS2307: Cannot find module 'svg-path-bbox' or its corresponding type declarations.
  There are types at 'C:/Mes projets web/SIREC/sirec-web-app/node_modules/svg-path-bbox/dist/types.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

version :
"typescript": "^5.4.2",
"svg-path-bbox": "^1.2.6",
"vite": "^5.1.6",

ts config : 

{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["src", "node_modules/vite-plugin-pwa/client.d.ts", "global.d.ts"],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}

Vite doesn't support anymore commonJS package, please help

**Comment by MALVEBaptiste** [comment]
resolve tempory : 

i added this line in file : vite-env.d.ts 

declare module "svg-path-bbox" {
  export default function svgPathBbox(path: string): [number, number, number, number];
}

Can you fix it ?

**Comment by mondeja** [comment]
You're using the ESNext target with Node module resolution.

> this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

What do you think that this is an error that should be fixed? Is because was working on v1.2.5?

**Comment by mondeja** [comment]
I'm wondering about the cause of the problem, not about your solution. There is other solutions available.

**Comment by tomkennedy22** [comment]
@MALVEBaptiste + @mondeja 
I'm also having this problem, I think it's an issue with types.d.ts that was introduced in this commit: https://github.com/mondeja/svg-path-bbox/commit/ad4cdbdc3e6776655e7eda4e010c5130738f9abf


```
node_modules/svg-path-bbox/dist/types.d.ts:9:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

export = svgPathBbox;
  ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mondeja** [comment]
See https://www.typescriptlang.org/docs/handbook/modules/reference.html#export--and-import--require

> When emitting CommonJS modules, TypeScript files can use a direct analog of `module.exports = ...` and `const mod = require("...")` JavaScript syntax

**Comment by mondeja** [comment]
> @MALVEBaptiste + @mondeja I'm also having this problem, I think it's an issue with types.d.ts that was introduced in this commit: [ad4cdbd](https://github.com/mondeja/svg-path-bbox/commit/ad4cdbdc3e6776655e7eda4e010c5130738f9abf)
> 
> ```
> node_modules/svg-path-bbox/dist/types.d.ts:9:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.
> 
> export = svgPathBbox;
>   ~~~~~~~~~~~~~~~~~~~~~
> ```

This problem has been solved because in v2 the library only uses named exports. Try it.
